### ISSUE TITLE
Error in migrating from 4.2.3 to 6.11.4

### ISSUE THREAD

**Issue by Eralph** [nodenv/nodenv-npm-migrate#9]
`$ nodenv migrate 4.2.3 6.11.4
npm ERR! addLocal Could not install /home/user1
npm ERR! Linux 3.11.0-26-generic
npm ERR! argv "/home/user1/.nodenv/versions/6.11.4/bin/node" "/home/user1/.nodenv/versions/6.11.4/bin/npm" "install" "--global"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user1/npm-debug.log`

**Comment by jasonkarns** [comment]
With 4.2.3 active, can you `npm ls --global --depth=0` ?

**Comment by jasonkarns** [comment]
stale
